-- 코드를 입력하세요
SELECT
    CAR_ID,
    -- DATEDIFF는 날짜 차이만 계산하므로 +1 (시작일 포함)
    ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY
    CAR_ID
HAVING
    AVG(DATEDIFF(END_DATE, START_DATE) + 1) >= 7
ORDER BY
    AVERAGE_DURATION DESC,
    CAR_ID DESC;