WITH RECURSIVE Time AS (
    SELECT 0 AS HOUR
    UNION
    SELECT HOUR + 1
    FROM Time
    WHERE HOUR < 23
)

SELECT 
    T.HOUR, 
    COUNT(A.ANIMAL_ID) AS COUNT
FROM Time T
LEFT JOIN ANIMAL_OUTS A 
    ON T.HOUR = HOUR(A.DATETIME)
GROUP BY T.HOUR
ORDER BY T.HOUR;