-- 내가 생각한 방식의 코드
WITH MaxSizePerYear AS (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS YR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM
        ECOLI_DATA
    GROUP BY
        YEAR(DIFFERENTIATION_DATE)
)

SELECT
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    (M.MAX_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV,
    E.ID
FROM
    ECOLI_DATA AS E
INNER JOIN
    MaxSizePerYear AS M ON YEAR(E.DIFFERENTIATION_DATE) = M.YR
ORDER BY
    YEAR ASC,
    YEAR_DEV ASC;
    
-- 최적화 코드 AI 제공
-- partition 사용이 더 적합할듯함
    
# SELECT
#     YEAR(DIFFERENTIATION_DATE) AS YEAR,
#     (MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE))) - SIZE_OF_COLONY AS YEAR_DEV,
#     ID
# FROM
#     ECOLI_DATA
# ORDER BY
#     YEAR ASC,
#     YEAR_DEV ASC;